title: Bryan Didier Márquez Álvarez # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, CDMX
  <br><br>
  Mi objetivo es contar historias con datos y ayudar a tomar decisiones basadas en datos, mediante la aplicación de una de las ciencias emergentes orientada a los negocios. Científico de Datos con habilidades en Machine Learning, Deep Learning, Bases de Datos y Visualización 
  <br><br>
  Tengo experiencia en análisis de datos, visualización y proyectos ágiles
  <br><br>
  <a href="https://www.linkedin.com/in/tulinkedin/">Entra a mi perfil de LinkedIn</a> 
  <br><br>
  <a href="/pdf/plantilla-curriculum-blanco.pdf">Mira mi Curriculum Vitae (CV) </a> 
  
theme: jekyll-theme-minimal
