title: Bryan Didier Márquez Álvarez # your name (or website title) here
logo: "/images/IMG-20230120-WA0005_3.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, CDMX
  <br><br>
  Científico de Datos con habilidades en Machine Learning, Deep Learning, Bases de Datos, Inteligencia de Negocios y Visualización 
  <br><br>
  He colaborado en el sector público, banca y seguros. Tengo experiencia en gestión de procesos, análisis de datos, visualización y proyectos ágiles
  <br><br>
  <a href="https://www.linkedin.com/in/bryan-marquez-alvarez/">Entra a mi perfil de LinkedIn</a> 
  <br><br>
  <a href="/pdf/CV-BRYAN_MARQUEZ.pdf">Mira mi Curriculum Vitae (CV) </a> 
  
theme: jekyll-theme-minimal
